### PR TITLE
2 initial refactor

### PR DESCRIPTION
**Pull request by mipoon**
Disable password protection.
Add initial code for a database.

### CODE REVIEW

**Review by Implyer — COMMENTED** [review]
I don't understand what it means. Help!

**Review by Fruitellah — COMMENTED** [review]
aloha

**Review by Fruitellah — APPROVED** [review]
TEST

**Review by Implyer — APPROVED** [review]
Yippee? I still don't understand... YIPEEEEE

**Comment by Implyer** [comment]
git tripping :O

**Pull request merged**
